# Generated by Django 2.2.2 on 2019-10-31 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0002_auto_20191031_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='/Users/mohamad/Desktop/dev/ticket/media/profile.png', null=True, upload_to=''),
        ),
    ]
