# Generated by Django 2.2.2 on 2019-11-01 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0003_auto_20191031_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='reserved',
        ),
        migrations.AddField(
            model_name='invoice',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoice', to='ticketapp.Ticket'),
        ),
        migrations.AddField(
            model_name='seat',
            name='status',
            field=models.CharField(choices=[('A', 'Available'), ('S', 'Sold'), ('M', 'Mine')], default='A', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('res_date_time', models.DateTimeField(auto_now_add=True)),
                ('pay_date_time', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reservation_bought', to='ticketapp.Profile')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_owned', to='ticketapp.Profile')),
                ('seat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ticketapp.Seat')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ticketapp.Ticket')),
            ],
            options={
                'unique_together': {('seat', 'profile')},
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoice', to='ticketapp.Reservation'),
        ),
    ]
