# Generated by Django 2.2.2 on 2019-10-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0003_auto_20191031_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to=''),
        ),
    ]
