# Generated by Django 2.2.2 on 2019-11-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0004_auto_20191101_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
