# Generated by Django 2.2.2 on 2019-11-01 16:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0005_ticket_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 11, 1, 16, 11, 53, 41796, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
