# Generated by Django 2.2.2 on 2019-11-02 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0006_invoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='gender',
            field=models.CharField(choices=[('f', 'female'), ('m', 'male'), ('t', 'trans')], max_length=2),
        ),
        migrations.AlterField(
            model_name='block',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='block', to='ticketapp.Hall'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female'), ('t', 'trans')], max_length=2),
        ),
        migrations.AlterField(
            model_name='row',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='row', to='ticketapp.Block'),
        ),
    ]
