# Generated by Django 2.2.2 on 2019-11-02 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0008_auto_20191102_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='pay_date_time',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='buyer',
        ),
    ]
