# Generated by Django 2.2.2 on 2019-11-03 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0009_auto_20191102_2103'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('key',)},
        ),
    ]
