# Generated by Django 2.2.2 on 2019-11-03 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0010_auto_20191103_1706'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together=set(),
        ),
    ]
