# Generated by Django 2.2.2 on 2019-11-03 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0011_auto_20191103_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='block', to='ticketapp.Hall'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='ticketapp.Reservation'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketapp.Terminal'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='ticketapp.Ticket'),
        ),
        migrations.AlterField(
            model_name='paymentlinks',
            name='terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketapp.Terminal'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticketapp.Major'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticketapp.Ticket'),
        ),
        migrations.AlterField(
            model_name='row',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='row', to='ticketapp.Block'),
        ),
    ]
