# Generated by Django 2.2.2 on 2019-11-03 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0012_auto_20191103_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='title',
            new_name='name',
        ),
    ]
