# Generated by Django 2.2.2 on 2019-11-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0013_auto_20191103_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='token',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
