# Generated by Django 2.2.2 on 2019-11-04 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0004_auto_20191031_1550'),
        ('ticketapp', '0014_terminal_token'),
    ]

    operations = [
    ]
