# Generated by Django 2.2.2 on 2019-11-05 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0017_invoice_profile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=set(),
        ),
    ]
