# Generated by Django 2.2.2 on 2019-11-05 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0016_auto_20191105_1648'),
        ('ticketapp', '0018_auto_20191105_1723'),
    ]

    operations = [
    ]
