# Generated by Django 2.2.2 on 2019-11-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0019_merge_20191105_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='qr',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
